FROM lambci/lambda-base-2 AS runtime

FROM lambci/lambda-base-2:build

RUN yum install -y bash

COPY --from=runtime /usr/lib64 /lib64.runtime

COPY entrypoint.sh /entrypoint.sh

WORKDIR /src

ENTRYPOINT ["/entrypoint.sh"]
